# Generated by Django 4.0.4 on 2022-04-19 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djeet', '0003_alter_djeet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djeet',
            name='body',
            field=models.CharField(max_length=255, verbose_name='djeetext'),
        ),
    ]
