# Generated by Django 4.0.4 on 2022-04-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djeet', '0004_alter_djeet_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djeet',
            name='body',
            field=models.CharField(max_length=255),
        ),
    ]
