# Generated by Django 4.0.4 on 2022-04-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djeet', '0005_alter_djeet_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='djeet',
            name='djeetext',
            field=models.CharField(default='Djeet goes here.', max_length=255),
        ),
    ]
